language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: "-----BEGIN PUBLIC KEY-----MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA7oG2ZBxU0lZ3y5Jq1g3MeflKF02owwCnGHksERvSOAajW4Ato32DLE0gLA8xbB0ate/kgCF4HKkLnvbuzX8GG3YBoCo4hyEoujoUlIMQTiyhdXyw3HIYzQ1Pc2jr+jDfsPl/wVYY4BeyY23I+nZkQP7uswd+tJGIp1mm98A4ZOgo8tM0eIAzu/3xZcmD/nVFAH3/cJjMIEtqlKImXjzRXQW7878oLGE0DaIkqEI60hgXPBpiQwh5D9t7YMMucJOZ+8rfcBN9dtC9IOPpiGxFXXd1zt3fC3yqXHMF+DorRBLK0q7dgzQX9Y2nlJedJfwITBC5KM6P8FEcVj0XCq0qxtFgv+EUPaPixvWpGQxQDKZZCWs5huaR45RkcyfzI8QzXHoESMKevtP6sHzCiBv5HKIaeXVUtsfOaLqz50xbhNVWKk6AnnXxZBmGV8DL6D3AUeSPGd18dfLr6VcTJ40H+4j9ZxcTa0iccwVyVCMQIkGnxHYKsUsDMS3jvYVUgptX1hwY61fHXY3MLbINXhnj6gopybLDWVQfB+4uj3V3Qi2HkaDGpEbwPsEqTLm8Khdt2CYJImkOvWCgRMh+PWKfwSvP5Tn/eTT6RGWjfZxL6CxnLUMfSgwEJolNN5BbHGB8xTLLyT/uPOoTNIS2GpVI3ehTZAfYwGztCRLd6fb78X0CAwEAAQ==-----END PUBLIC KEY-----"
